server:
  port: 9527
spring:
  application:
    name: exam-gateway-server
  cloud:
    gateway:
      routes:
        - id: exam-paper-server
          uri: http://localhost:8080
          predicates:
            - Path=/exam-paper/**
        - id: answer-paper-server
          uri: http://localhost:8090
          predicates:
            - Path=/answer-paper/**
        - id: account-center-server
          uri: http://localhost:9000
          predicates:
            - Path=/account-center/**
